on:
  push:
    branches:
    - main
    paths:
    - "bundles/http2-rfc7540/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: setup docker
      uses: docker/setup-buildx-action@v1

    - name: login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and push
      run: |
        go build -o bin/protospec .
        ./bin/protospec -s bundles/http2-rfc7540 ghcr.io/summerwind/protospec-bundle-http2-rfc7540:latest
